### ISSUE TITLE
Type System TODO

### ISSUE THREAD

**Issue by sezna** [ch-systems/petr#145]
TODO:
- [ ] Typeclasses
- [ ] Constrained types ('int without `0`, for example -- ranges)
- [ ] Specific types for user defined types
- [ ] Deduplicate constraints before solving
- [ ] More tests in type checker
- [ ] Document and organize typecheck/lib.rs
